name: veacos
description: Veacos 1.0.0.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  local_auth: ^1.1.8
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  build_runner: ^2.1.10
  path_provider: ^2.0.10
  hive: ^2.1.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  http: ^0.13.4
  badges: ^2.0.2
  google_sign_in: ^5.3.0
  dio: ^4.0.6
  file_picker: ^4.5.1
  flutter_session_manager: ^1.0.3
  universal_html: ^2.0.8
  flutter_local_notifications: ^9.5.2
  show_update_dialog: ^1.0.10
  cached_network_image: ^3.2.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.2
  socket_io_client: ^1.0.2
  image_cropper: ^2.0.3
  uni_links: ^0.5.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  mockito: ^5.2.0
  http_mock_adapter: ^0.3.3
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#F0FEFD"
  image: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/exe/
    - assets/img/
    - assets/icon/icon.png

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  chrome: flutter run -d chrome --web-renderer html --web-port 52230
  build_web: flutter build web --web-renderer html && scp -r .\build\web\* root@45.82.75.3:/home/munatask/public_html/
  build_windows: flutter build windows
  build_bundle: flutter build appbundle --build-name=2.1.4 --build-number=214 --no-tree-shake-icons
  build_apk: flutter build apk --build-name=2.1.4+4 --build-number=214 --no-tree-shake-icons
  launch_icon: flutter pub run flutter_launcher_icons:main
  launch_splash: flutter pub run flutter_native_splash:create
